# Generated by Django 4.2.1 on 2024-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='files/news/')),
                ('date_created', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
