# Generated by Django 4.2.1 on 2024-11-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_smartnotemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartnotemedia',
            name='media_type',
        ),
    ]
