# Generated by Django 4.2.1 on 2024-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_image_image_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativedata',
            name='project_capacity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
