# Generated by Django 4.2.1 on 2024-12-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_informativedata_project_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.TextField(max_length=10000)),
                ('text_2', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='intro/image')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('usage_procedure', models.TextField(verbose_name=10000)),
                ('offer', models.TextField(verbose_name=20000)),
            ],
        ),
    ]
