# Generated by Django 4.2.1 on 2024-12-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_intro_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='AboutDocument',
        ),
    ]
