# Generated by Django 4.2.1 on 2025-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_phone_aboutdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alldata',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
