# Generated by Django 4.2.1 on 2025-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alldata_top_alldata_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('android_version', models.CharField(max_length=255)),
            ],
        ),
    ]
