# Generated by Django 4.2.1 on 2025-01-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_devices_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='user',
        ),
    ]
