# Generated by Django 5.1.6 on 2025-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='text_1_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='text_1_ru',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='text_1_uz',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
