# Generated by Django 5.1.6 on 2025-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_intro_text_1_en_intro_text_1_ru_intro_text_1_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='text_2_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='text_2_ru',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='text_2_uz',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
