# Generated by Django 4.2.1 on 2024-11-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_salom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salom',
        ),
    ]
