# Generated by Django 5.1.6 on 2025-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
