# Generated by Django 5.2.4 on 2025-07-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_notification_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
    ]
