# Generated by Django 5.1.6 on 2025-02-14 16:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default=2, max_length=355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
