# Generated by Django 5.1.6 on 2025-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_about_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
