# Generated by Django 5.2.4 on 2025-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tin',
            field=models.CharField(default=1, max_length=14, unique=True),
        ),
    ]
