# Generated by Django 5.2.4 on 2025-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tin',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
