# Generated by Django 5.2.4 on 2025-08-18 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamni +99890XXXXXXX formatida kiriting.', regex='^\\+998(33|50|55|77|88|90|91|93|94|95|97|98|99)\\d{7}$')], verbose_name='Phone number'),
        ),
    ]
